-- Create database
CREATE DATABASE cyber_aptitude_db;

-- Connect to database
\c cyber_aptitude_db;

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Participants table
CREATE TABLE participants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    full_name VARCHAR(255),
    institution VARCHAR(255),
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_test_date TIMESTAMP,
    total_tests_taken INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tests table
CREATE TABLE tests (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    participant_id UUID REFERENCES participants(id) ON DELETE CASCADE,
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP,
    duration INT, -- in seconds
    status VARCHAR(20) DEFAULT 'in_progress',
    score DECIMAL(5,2),
    category_scores JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Questions table
CREATE TABLE questions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    question_text TEXT NOT NULL,
    category VARCHAR(50) NOT NULL,
    difficulty VARCHAR(20) DEFAULT 'medium',
    options JSONB NOT NULL,
    correct_answer VARCHAR(1) NOT NULL,
    explanation TEXT,
    points INT DEFAULT 1,
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Answers table
CREATE TABLE answers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    test_id UUID REFERENCES tests(id) ON DELETE CASCADE,
    question_id UUID REFERENCES questions(id) ON DELETE CASCADE,
    selected_option VARCHAR(1),
    is_correct BOOLEAN,
    time_taken INT, -- in seconds
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Admin users table
CREATE TABLE admins (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    role VARCHAR(50) DEFAULT 'admin',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP
);

-- Insert sample admin (password: Admin@123)
INSERT INTO admins (username, password_hash, email, role) 
VALUES ('admin', '$2a$10$YourHashedPasswordHere', 'admin@ur.afretec.mastercard', 'super_admin');

-- Insert sample questions
INSERT INTO questions (question_text, category, difficulty, options, correct_answer, explanation, points) VALUES
-- CYBER FOUNDATIONS & RECONNAISSANCE
('What is the primary goal of reconnaissance in cybersecurity?', 'CYBER_FOUNDATIONS', 'easy', 
 '{"A": "To attack systems", "B": "To gather information about target systems", "C": "To implement firewalls", "D": "To encrypt data"}', 
 'B', 
 'Reconnaissance is the first phase of ethical hacking where information about the target is gathered.', 1),

('Which tool is commonly used for network scanning and reconnaissance?', 'CYBER_FOUNDATIONS', 'medium', 
 '{"A": "Nmap", "B": "Wireshark", "C": "Metasploit", "D": "Burp Suite"}', 
 'A', 
 'Nmap (Network Mapper) is the most popular tool for network discovery and security auditing.', 1),

-- LINUX FUNDAMENTALS
('What command is used to change file permissions in Linux?', 'LINUX_FUNDAMENTALS', 'easy', 
 '{"A": "chmod", "B": "chown", "C": "chgrp", "D": "perm"}', 
 'A', 
 'The chmod command is used to change the permissions of files and directories.', 1),

('Which command shows running processes in Linux?', 'LINUX_FUNDAMENTALS', 'medium', 
 '{"A": "ls", "B": "ps", "C": "top", "D": "Both B and C"}', 
 'D', 
 'Both ps and top commands show running processes in Linux.', 1),

-- ATTACK VECTORS & EXPLOITATION
('What is a SQL Injection attack?', 'ATTACK_VECTORS', 'medium', 
 '{"A": "Injection of SQL commands via input fields", "B": "Database encryption attack", "C": "SQL server DoS attack", "D": "SQL backup corruption"}', 
 'A', 
 'SQL Injection involves inserting malicious SQL code via input fields to manipulate databases.', 1),

('Which of these is NOT a common web application vulnerability?', 'ATTACK_VECTORS', 'hard', 
 '{"A": "Cross-Site Scripting (XSS)", "B": "Cross-Site Request Forgery (CSRF)", "C": "Secure Socket Layer (SSL)", "D": "Insecure Direct Object References"}', 
 'C', 
 'SSL is a security protocol, not a vulnerability.', 1),

-- DEFENSE & OPERATIONS
('What is the purpose of a Security Information and Event Management (SIEM) system?', 'DEFENSE_OPS', 'medium', 
 '{"A": "Real-time analysis of security alerts", "B": "Network scanning", "C": "Password cracking", "D": "Data encryption"}', 
 'A', 
 'SIEM systems provide real-time analysis of security alerts generated by network hardware and applications.', 1),

('Which is NOT a principle of defense in depth?', 'DEFENSE_OPS', 'hard', 
 '{"A": "Multiple layers of security", "B": "Single point of failure", "C": "Diverse defensive mechanisms", "D": "Redundant security controls"}', 
 'B', 
 'Defense in depth avoids single points of failure by implementing multiple security layers.', 1),

-- CAPSTONE & PORTFOLIO
('In incident response, what does the "Containment" phase involve?', 'CAPSTONE', 'medium', 
 '{"A": "Preventing further damage", "B": "Identifying the incident", "C": "Learning from the incident", "D": "Restoring systems"}', 
 'A', 
 'Containment focuses on preventing the incident from causing more damage.', 1),

('What is the main purpose of a cybersecurity portfolio?', 'CAPSTONE', 'easy', 
 '{"A": "To showcase practical skills and projects", "B": "To store encrypted files", "C": "To manage network devices", "D": "To document theoretical knowledge only"}', 
 'A', 
 'A portfolio demonstrates practical cybersecurity skills through completed projects and assessments.', 1);

-- Additional sample questions (complete the set of 25)
INSERT INTO questions (id, question_text, category, difficulty, options, correct_answer, explanation, points) VALUES
(uuid_generate_v4(), 'What does OSINT stand for in cybersecurity?', 'CYBER_FOUNDATIONS', 'medium', '{"A": "Open Source Intelligence", "B": "Operating System Integration", "C": "Online Security Interface", "D": "Official Security Investigation"}', 'A', 'OSINT stands for Open Source Intelligence, which involves gathering information from publicly available sources.', 1),
(uuid_generate_v4(), 'Which phase comes after reconnaissance in the ethical hacking process?', 'CYBER_FOUNDATIONS', 'medium', '{"A": "Scanning", "B": "Maintaining Access", "C": "Covering Tracks", "D": "Reporting"}', 'A', 'After reconnaissance, the next phase is scanning, where systems are scanned for vulnerabilities.', 1),
(uuid_generate_v4(), 'What is footprinting in cybersecurity?', 'CYBER_FOUNDATIONS', 'hard', '{"A": "Creating a profile of the target organization", "B": "Encrypting data footprints", "C": "Deleting system logs", "D": "Monitoring network traffic"}', 'A', 'Footprinting is the process of gathering information about a target system to create a profile of the organization.', 1),
(uuid_generate_v4(), 'What is the purpose of the sudo command?', 'LINUX_FUNDAMENTALS', 'easy', '{"A": "To switch users", "B": "To execute commands with superuser privileges", "C": "To shutdown the system", "D": "To display system information"}', 'B', 'The sudo command allows a permitted user to execute a command as the superuser or another user.', 1),
(uuid_generate_v4(), 'Which command is used to search for text patterns in files?', 'LINUX_FUNDAMENTALS', 'medium', '{"A": "find", "B": "grep", "C": "locate", "D": "search"}', 'B', 'The grep command is used to search text or search the given file for lines containing a match to the given strings.', 1),
(uuid_generate_v4(), 'What does the command "ls -la" display?', 'LINUX_FUNDAMENTALS', 'medium', '{"A": "List files in alphabetical order", "B": "List all files including hidden ones with details", "C": "List only directories", "D": "List files by size"}', 'B', 'ls -la lists all files (including hidden ones) in long format with detailed information.', 1),
(uuid_generate_v4(), 'What is a buffer overflow attack?', 'ATTACK_VECTORS', 'hard', '{"A": "Writing data beyond the allocated buffer memory", "B": "Overloading network buffers", "C": "Filling disk space", "D": "Flooding email servers"}', 'A', 'Buffer overflow occurs when a program writes data to a buffer beyond its allocated memory.', 1),
(uuid_generate_v4(), 'What is phishing?', 'ATTACK_VECTORS', 'easy', '{"A": "A social engineering attack to steal sensitive information", "B": "A network flooding attack", "C": "A type of virus", "D": "A hardware vulnerability"}', 'A', 'Phishing is a social engineering attack where attackers impersonate legitimate entities to steal sensitive data.', 1),
(uuid_generate_v4(), 'What is a zero-day vulnerability?', 'ATTACK_VECTORS', 'medium', '{"A": "A vulnerability known for zero days", "B": "A flaw unknown to the vendor with no patch available", "C": "A vulnerability that affects zero systems", "D": "A minor security issue"}', 'B', 'A zero-day vulnerability is a software flaw unknown to the vendor with no available patch.', 1),
(uuid_generate_v4(), 'What is the purpose of a firewall?', 'DEFENSE_OPS', 'easy', '{"A": "Monitor and control network traffic", "B": "Encrypt data transmissions", "C": "Scan for viruses", "D": "Manage user passwords"}', 'A', 'A firewall monitors and controls incoming and outgoing network traffic based on predetermined security rules.', 1),
(uuid_generate_v4(), 'What does IDS stand for?', 'DEFENSE_OPS', 'easy', '{"A": "Intrusion Detection System", "B": "Internet Defense System", "C": "Internal Data Security", "D": "Integrated Defense Solution"}', 'A', 'IDS stands for Intrusion Detection System, which monitors network traffic for suspicious activity.', 1),
(uuid_generate_v4(), 'What is penetration testing?', 'DEFENSE_OPS', 'medium', '{"A": "Authorized simulated cyberattack on a computer system", "B": "Testing network speed", "C": "Checking software compatibility", "D": "Validating user permissions"}', 'A', 'Penetration testing is an authorized simulated attack performed to evaluate security.', 1),
(uuid_generate_v4(), 'What is the first step in the incident response process?', 'CAPSTONE', 'easy', '{"A": "Preparation", "B": "Identification", "C": "Containment", "D": "Eradication"}', 'A', 'Preparation is the first step, involving developing policies and procedures before incidents occur.', 1),
(uuid_generate_v4(), 'What does NIST stand for in cybersecurity frameworks?', 'CAPSTONE', 'medium', '{"A": "National Institute of Standards and Technology", "B": "Network International Security Team", "C": "National Internet Security Taskforce", "D": "Network Infrastructure Security Technology"}', 'A', 'NIST stands for National Institute of Standards and Technology, which develops cybersecurity frameworks.', 1),
(uuid_generate_v4(), 'What is risk assessment in cybersecurity?', 'CAPSTONE', 'hard', '{"A": "Identifying, analyzing, and evaluating risks", "B": "Testing system vulnerabilities", "C": "Implementing security controls", "D": "Monitoring network traffic"}', 'A', 'Risk assessment involves identifying, analyzing, and evaluating potential risks to an organization.', 1);

-- Create indexes for better performance
CREATE INDEX idx_participants_email ON participants(email);
CREATE INDEX idx_tests_participant_id ON tests(participant_id);
CREATE INDEX idx_tests_status ON tests(status);
CREATE INDEX idx_questions_category ON questions(category);
CREATE INDEX idx_answers_test_id ON answers(test_id);
CREATE INDEX idx_answers_question_id ON answers(question_id);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_participants_updated_at 
    BEFORE UPDATE ON participants 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();