-- Create database
CREATE DATABASE cyber_aptitude_db;

-- Connect to database
\c cyber_aptitude_db;

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Participants table
CREATE TABLE participants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    full_name VARCHAR(255),
    institution VARCHAR(255),
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_test_date TIMESTAMP,
    total_tests_taken INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tests table
CREATE TABLE tests (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    participant_id UUID REFERENCES participants(id) ON DELETE CASCADE,
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP,
    duration INT, -- in seconds
    status VARCHAR(20) DEFAULT 'in_progress',
    score DECIMAL(5,2),
    category_scores JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Questions table
CREATE TABLE questions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    question_text TEXT NOT NULL,
    category VARCHAR(50) NOT NULL,
    difficulty VARCHAR(20) DEFAULT 'medium',
    options JSONB NOT NULL,
    correct_answer VARCHAR(1) NOT NULL,
    explanation TEXT,
    points INT DEFAULT 1,
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Answers table
CREATE TABLE answers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    test_id UUID REFERENCES tests(id) ON DELETE CASCADE,
    question_id UUID REFERENCES questions(id) ON DELETE CASCADE,
    selected_option VARCHAR(1),
    is_correct BOOLEAN,
    time_taken INT, -- in seconds
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Admin users table
CREATE TABLE admins (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    role VARCHAR(50) DEFAULT 'admin',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP
);

-- Insert sample admin (password: Admin@123)
INSERT INTO admins (username, password_hash, email, role) 
VALUES ('admin', '$2a$10$YourHashedPasswordHere', 'admin@ur.afretec.mastercard', 'super_admin');

-- Insert sample questions
INSERT INTO questions (question_text, category, difficulty, options, correct_answer, explanation, points) VALUES
-- CYBER FOUNDATIONS & RECONNAISSANCE
('What is the primary goal of reconnaissance in cybersecurity?', 'CYBER_FOUNDATIONS', 'easy', 
 '{"A": "To attack systems", "B": "To gather information about target systems", "C": "To implement firewalls", "D": "To encrypt data"}', 
 'B', 
 'Reconnaissance is the first phase of ethical hacking where information about the target is gathered.', 1),

('Which tool is commonly used for network scanning and reconnaissance?', 'CYBER_FOUNDATIONS', 'medium', 
 '{"A": "Nmap", "B": "Wireshark", "C": "Metasploit", "D": "Burp Suite"}', 
 'A', 
 'Nmap (Network Mapper) is the most popular tool for network discovery and security auditing.', 1),

-- LINUX FUNDAMENTALS
('What command is used to change file permissions in Linux?', 'LINUX_FUNDAMENTALS', 'easy', 
 '{"A": "chmod", "B": "chown", "C": "chgrp", "D": "perm"}', 
 'A', 
 'The chmod command is used to change the permissions of files and directories.', 1),

('Which command shows running processes in Linux?', 'LINUX_FUNDAMENTALS', 'medium', 
 '{"A": "ls", "B": "ps", "C": "top", "D": "Both B and C"}', 
 'D', 
 'Both ps and top commands show running processes in Linux.', 1),

-- ATTACK VECTORS & EXPLOITATION
('What is a SQL Injection attack?', 'ATTACK_VECTORS', 'medium', 
 '{"A": "Injection of SQL commands via input fields", "B": "Database encryption attack", "C": "SQL server DoS attack", "D": "SQL backup corruption"}', 
 'A', 
 'SQL Injection involves inserting malicious SQL code via input fields to manipulate databases.', 1),

('Which of these is NOT a common web application vulnerability?', 'ATTACK_VECTORS', 'hard', 
 '{"A": "Cross-Site Scripting (XSS)", "B": "Cross-Site Request Forgery (CSRF)", "C": "Secure Socket Layer (SSL)", "D": "Insecure Direct Object References"}', 
 'C', 
 'SSL is a security protocol, not a vulnerability.', 1),

-- DEFENSE & OPERATIONS
('What is the purpose of a Security Information and Event Management (SIEM) system?', 'DEFENSE_OPS', 'medium', 
 '{"A": "Real-time analysis of security alerts", "B": "Network scanning", "C": "Password cracking", "D": "Data encryption"}', 
 'A', 
 'SIEM systems provide real-time analysis of security alerts generated by network hardware and applications.', 1),

('Which is NOT a principle of defense in depth?', 'DEFENSE_OPS', 'hard', 
 '{"A": "Multiple layers of security", "B": "Single point of failure", "C": "Diverse defensive mechanisms", "D": "Redundant security controls"}', 
 'B', 
 'Defense in depth avoids single points of failure by implementing multiple security layers.', 1),

-- CAPSTONE & PORTFOLIO
('In incident response, what does the "Containment" phase involve?', 'CAPSTONE', 'medium', 
 '{"A": "Preventing further damage", "B": "Identifying the incident", "C": "Learning from the incident", "D": "Restoring systems"}', 
 'A', 
 'Containment focuses on preventing the incident from causing more damage.', 1),

('What is the main purpose of a cybersecurity portfolio?', 'CAPSTONE', 'easy', 
 '{"A": "To showcase practical skills and projects", "B": "To store encrypted files", "C": "To manage network devices", "D": "To document theoretical knowledge only"}', 
 'A', 
 'A portfolio demonstrates practical cybersecurity skills through completed projects and assessments.', 1);

-- Create indexes for better performance
CREATE INDEX idx_participants_email ON participants(email);
CREATE INDEX idx_tests_participant_id ON tests(participant_id);
CREATE INDEX idx_tests_status ON tests(status);
CREATE INDEX idx_questions_category ON questions(category);
CREATE INDEX idx_answers_test_id ON answers(test_id);
CREATE INDEX idx_answers_question_id ON answers(question_id);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_participants_updated_at 
    BEFORE UPDATE ON participants 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();